version: '3.4'

services:
  usecasedistribuitedcachewithredis:
    image: ${DOCKER_REGISTRY-}usecasedistribuitedcachewithredis
    build:
      context: .
      dockerfile: UseCaseDistribuitedCacheWithRedis/Dockerfile
    container_name: api
    networks:
      - rede-interna
  redis:
    image: redis:latest
    container_name: redis
    volumes:
        - ./:/data
    ports:
      - "16379:6379"
    networks:
      - rede-interna

networks: 
    rede-interna:
        driver: bridge